---
# SSH
ssh_public_key_files:
    - ~/.ssh/id_rsa.pub

# -------------------------------
# Firewall Configuration (firewalld)
# -------------------------------

private_network_subnet: "10.0.0.0/16"

whitelisted_ips:
    # Your IP from which you would like to access the cluster
    # Can be a home IP (if you have a fixed IP) or a server on the
    # internet you use for administrating other machines
    # - "1.1.1.1/32"

#
# Services/ports that should be allowed on the firewall to the public
# (port identified with a service name)
#
open_services:
    - ssh
    - http
    - https

#
# Ports that should be allowed on the firewall to the public
#
open_ports:
#    # begin: Mailu Email services ports (comment them out if Mailu will not be installed)
#    - "25/tcp"    # smtp
#    - "587/tcp"   # smtpd
#    - "465/tcp"   # smtps
#    - "993/tcp"   # imaps
#    - "143/tcp"   # imap
#    - "995/tcp"   # pop3s
#    - "110/tcp"   # pop3
#    # end: Mailu Email services ports



# -------------------------------
# Admin email notifications
# -------------------------------

admin_email: admin@example.com
notifications_email: admin@example.com


# -------------------------------
# Fail2Ban configuration
# -------------------------------

#fail2ban_services:
#    - name: ssh

# Fail2ban
fail2ban_sender: andromeda-k8s-cluster@example.com

fail2ban_ignoreips:
    # See whitelisted IPs
    # - 1.1.1.1

fail2ban_destemail: admin@example.com

