---
- name: Node provisioning
  hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
      - role: ansible-bootstrap-role
        tags: bootstrap
      - role: ansible-postfix-role
        tags: postfix
      - role: ansible-users-role
        tags: users
      - role: ansible-fail2ban-role
        tags: fail2ban
      - role: ansible-hcloud-floating-ip-role
        tags: floating_ip
      - role: ansible-firewalld-role
        tags: firewalld
      - role: ansible-docker-role
        tags: docker
#      - role: ansible-kernelcare-role
#        tags: kernelcare
