---
- name: Node provisioning
  hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
      - role: ansible-bootstrap-role
        tags: bootstrap
      # If Mailu will be installed,  postfix cannot run on the hosts (port conflict)
      # If Mailu is not installed, uncomment the Postfix role to include it
      # - role: ansible-postfix-role
      #   tags: postfix
      - role: ansible-users-role
        tags: users
      - role: ansible-fail2ban-role
        tags: fail2ban
      - role: ansible-hcloud-floating-ip-role
        tags: floating_ip
# TODO: After the migration to Kubernetes 1.19 + Rancher 2.5, there are unresolved
#       firewall conflicts, so FirewallD CANNOT be used until we find out which
#       ports need to be handled differently
#      - role: ansible-firewalld-role
#        tags: firewalld
      - role: ansible-docker-role
        tags: docker
#      - role: ansible-kernelcare-role
#        tags: kernelcare
